site_name: baseflow
site_url: https://github.com/BYU-Hydroinformatics/baseflow/blob/merge-my-changes/
site_author: Xueyi Li

theme:
  name: material
  palette:
    primary: cyan
  features:
    - content.code.copy
    - content.code.select
    - navigation.expand
    - navigation.path
    - navigation.footer
    - toc.follow
    - toc.integrate
nav:
  - Home: index.md
  - API:
      - Separation: api.md
      - Utils: utils.md
  - Instructions: instructions.md

plugins:
  - search
  - mkdocstrings
  - include-markdown:
      comments: false

markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - markdown_include.include:
      base_path: docs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
