site_name: baseflow
theme: material
nav:
  - Home: index.md
  - API:
      - Separation: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
