site_name: baseflow
theme:
  name: material
  palette:
    primary: cyan
  features:
    - content.code.copy
    - content.code.select
    - navigation.expand
    - navigation.path
    - navigation.footer
    - toc.follow
    - toc.integrate
nav:
  - Home: index.md
  - API:
      - Separation: api.md
      - Estimate: estimate.md
      - Utils: utils.md
  - Instructions: instructions.md
  

features:
  - toc.integrate
  
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/mermaid@8.9.2/dist/mermaid.min.js
